### PR TITLE
Golie info should support remote resources transparently

### PR DESCRIPTION
**Pull request by isimluk**
```
golie info https://atopathways.redhatgov.io/compliance-as-code/scap/feed.json
```

### CODE REVIEW

**Comment by redhatrises** [comment]
Just an organization question, does it make sense to have acquire.go under utils vs some other directory?

**Comment by isimluk** [comment]
Yeah, I don't envision too many `acquireXYZ` methods. Hence I was a bit hesitant to create separate package.

**Comment by isimluk** [comment]
Will gladly & swiftly move it around if you like... :+1:

**Comment by redhatrises** [comment]
We can decide later. Merging for now.

**Pull request merged**
